name: Release

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Create new tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}